services:
  api:
    build:
      context: ./api-rh
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "5173:80"
    restart: unless-stopped
